# Production Docker Compose for Google Cloud Run
version: '3.8'

services:
  backend:
    build: .
    container_name: hackathoon-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${PORT:-8080}
      DATABASE_URL: ${DATABASE_URL}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      API_VERSION: v1
      API_PREFIX: /api/v1
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      BCRYPT_ROUNDS: 12
      MAX_FILE_SIZE: 10485760
      UPLOAD_DIR: /tmp/uploads
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - /tmp/uploads:/app/uploads
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm start
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8080}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s